# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Michael Eaton
tagline:          Random Stuff
url:              http://michaeleaton.co.uk
paginate:         1
baseurl:          /
author:
  name:           Michael Eaotn
  url:            https://twitter.com/mikeeaton
  email:          michaeleaton@hotmail.co.uk

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
